//! Cross-pane coordination logic for the Impulse Agent.
//!
//! Aggregates insights from the context lifecycle extractor and generates
//! coordination recommendations using the LLM provider.

use crate::context_lifecycle::types::{ExtractedInsight, InsightType};

/// A coordination recommendation generated by the Impulse Agent.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Recommendation {
    pub recommendation_type: RecommendationType,
    pub panes_involved: Vec<String>,
    pub description: String,
    pub action: String,
}

/// Types of coordination recommendations.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RecommendationType {
    FileConflict,
    ErrorAssist,
    CrossPaneSync,
    TaskComplete,
}

impl RecommendationType {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::FileConflict => "file_conflict",
            Self::ErrorAssist => "error_assist",
            Self::CrossPaneSync => "cross_pane_sync",
            Self::TaskComplete => "task_complete",
        }
    }
}

/// Detects file conflicts across panes (same file modified by multiple agents).
pub fn detect_file_conflicts(insights: &[ExtractedInsight]) -> Vec<Recommendation> {
    use std::collections::HashMap;

    // Group file modification insights by content (which contains the file path)
    let mut file_to_panes: HashMap<String, Vec<String>> = HashMap::new();
    for insight in insights {
        if insight.insight_type == InsightType::FileModified {
            file_to_panes
                .entry(insight.content.clone())
                .or_default()
                .push(format!("pane-{}", insight.pane_id));
        }
    }

    // Only flag when 2+ panes touch the same file
    file_to_panes
        .into_iter()
        .filter(|(_, panes)| panes.len() > 1)
        .map(|(file, panes)| Recommendation {
            recommendation_type: RecommendationType::FileConflict,
            panes_involved: panes,
            description: format!("Multiple agents modifying: {}", file),
            action: "Coordinate changes to avoid merge conflicts".to_string(),
        })
        .collect()
}

/// Detects errors in one pane that might be caused by another pane's changes.
pub fn detect_cross_pane_errors(insights: &[ExtractedInsight]) -> Vec<Recommendation> {
    let errors: Vec<&ExtractedInsight> = insights
        .iter()
        .filter(|i| i.insight_type == InsightType::ErrorEncountered)
        .collect();

    let modifications: Vec<&ExtractedInsight> = insights
        .iter()
        .filter(|i| i.insight_type == InsightType::FileModified)
        .collect();

    let mut recommendations = Vec::new();

    for error in &errors {
        // Check if any other pane modified files around the same time
        let related_mods: Vec<&ExtractedInsight> = modifications
            .iter()
            .filter(|m| {
                m.pane_id != error.pane_id
                    && (error.timestamp - m.timestamp).num_seconds().abs() < 120
            })
            .copied()
            .collect();

        if !related_mods.is_empty() {
            let panes: Vec<String> = std::iter::once(format!("pane-{}", error.pane_id))
                .chain(related_mods.iter().map(|m| format!("pane-{}", m.pane_id)))
                .collect();

            let mod_files: Vec<&str> = related_mods.iter().map(|m| m.content.as_str()).collect();

            recommendations.push(Recommendation {
                recommendation_type: RecommendationType::ErrorAssist,
                panes_involved: panes,
                description: format!(
                    "Error in pane-{} may relate to changes in: {}",
                    error.pane_id,
                    mod_files.join(", ")
                ),
                action: format!(
                    "Check if recent modifications to {} caused: {}",
                    mod_files[0], error.content
                ),
            });
        }
    }

    recommendations
}

/// Aggregate all insights into pane-keyed summaries for coordination prompts.
pub fn aggregate_pane_summaries(insights: &[ExtractedInsight]) -> Vec<(String, Vec<String>)> {
    use std::collections::BTreeMap;

    let mut pane_map: BTreeMap<usize, Vec<String>> = BTreeMap::new();
    for insight in insights {
        pane_map.entry(insight.pane_id).or_default().push(format!(
            "[{}] {}",
            insight.insight_type.as_str(),
            insight.content
        ));
    }

    pane_map
        .into_iter()
        .map(|(pid, summaries)| (format!("pane-{}", pid), summaries))
        .collect()
}

/// Run all local (non-LLM) coordination checks and return recommendations.
pub fn run_local_coordination(insights: &[ExtractedInsight]) -> Vec<Recommendation> {
    let mut all = Vec::new();
    all.extend(detect_file_conflicts(insights));
    all.extend(detect_cross_pane_errors(insights));
    all
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::context_lifecycle::types::AgentKind;
    use chrono::Utc;

    fn make_insight(pane_id: usize, insight_type: InsightType, content: &str) -> ExtractedInsight {
        ExtractedInsight {
            pane_id,
            agent_kind: AgentKind::ClaudeCode,
            timestamp: Utc::now(),
            insight_type,
            content: content.to_string(),
        }
    }

    #[test]
    fn test_detect_file_conflicts_none() {
        let insights = vec![
            make_insight(1, InsightType::FileModified, "src/main.rs"),
            make_insight(2, InsightType::FileModified, "src/lib.rs"),
        ];
        let conflicts = detect_file_conflicts(&insights);
        assert!(conflicts.is_empty());
    }

    #[test]
    fn test_detect_file_conflicts_found() {
        let insights = vec![
            make_insight(1, InsightType::FileModified, "src/main.rs"),
            make_insight(2, InsightType::FileModified, "src/main.rs"),
        ];
        let conflicts = detect_file_conflicts(&insights);
        assert_eq!(conflicts.len(), 1);
        assert_eq!(
            conflicts[0].recommendation_type,
            RecommendationType::FileConflict
        );
        assert_eq!(conflicts[0].panes_involved.len(), 2);
    }

    #[test]
    fn test_detect_cross_pane_errors() {
        let now = Utc::now();
        let insights = vec![
            ExtractedInsight {
                pane_id: 1,
                agent_kind: AgentKind::ClaudeCode,
                timestamp: now,
                insight_type: InsightType::FileModified,
                content: "src/lib.rs".to_string(),
            },
            ExtractedInsight {
                pane_id: 2,
                agent_kind: AgentKind::OpenCode,
                timestamp: now,
                insight_type: InsightType::ErrorEncountered,
                content: "cannot find module lib".to_string(),
            },
        ];
        let errors = detect_cross_pane_errors(&insights);
        assert_eq!(errors.len(), 1);
        assert_eq!(
            errors[0].recommendation_type,
            RecommendationType::ErrorAssist
        );
    }

    #[test]
    fn test_aggregate_pane_summaries() {
        let insights = vec![
            make_insight(1, InsightType::FileModified, "src/main.rs"),
            make_insight(1, InsightType::TaskCompleted, "tests pass"),
            make_insight(2, InsightType::ErrorEncountered, "compile error"),
        ];
        let summaries = aggregate_pane_summaries(&insights);
        assert_eq!(summaries.len(), 2);
        assert_eq!(summaries[0].0, "pane-1");
        assert_eq!(summaries[0].1.len(), 2);
        assert_eq!(summaries[1].0, "pane-2");
        assert_eq!(summaries[1].1.len(), 1);
    }

    #[test]
    fn test_run_local_coordination_empty() {
        let recs = run_local_coordination(&[]);
        assert!(recs.is_empty());
    }

    #[test]
    fn test_recommendation_type_as_str() {
        assert_eq!(RecommendationType::FileConflict.as_str(), "file_conflict");
        assert_eq!(RecommendationType::ErrorAssist.as_str(), "error_assist");
        assert_eq!(
            RecommendationType::CrossPaneSync.as_str(),
            "cross_pane_sync"
        );
        assert_eq!(RecommendationType::TaskComplete.as_str(), "task_complete");
    }
}
