//! Cross-pane coordination logic for the Impulse Agent.
//!
//! Aggregates insights from the context lifecycle extractor and generates
//! coordination recommendations using the LLM provider.

use crate::context_lifecycle::intent::IntentCategory;
use crate::context_lifecycle::types::{ExtractedInsight, InsightType};
use std::collections::HashMap;

/// Resolution strategy for file conflicts.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ConflictResolution {
    Merge,
    AcceptTheirs,
    AcceptMine,
    Rebase,
}

impl ConflictResolution {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Merge => "merge",
            Self::AcceptTheirs => "accept_theirs",
            Self::AcceptMine => "accept_mine",
            Self::Rebase => "rebase",
        }
    }

    pub fn description(&self) -> &'static str {
        match self {
            Self::Merge => "Manually merge changes from both agents",
            Self::AcceptTheirs => "Accept the other agent's changes",
            Self::AcceptMine => "Keep my changes",
            Self::Rebase => "Rebase on top of other agent's changes",
        }
    }
}

/// A coordination recommendation generated by the Impulse Agent.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Recommendation {
    pub recommendation_type: RecommendationType,
    pub panes_involved: Vec<String>,
    pub description: String,
    pub action: String,
    /// Priority score (0--100). Higher = more urgent.
    /// Base priority comes from recommendation type; intent modifiers adjust it.
    #[serde(default = "default_priority")]
    pub priority: u8,
}

fn default_priority() -> u8 {
    50
}

/// Full coordination result including recommendations and pane summaries.
/// Used by the daemon to return a richer response than just recommendations.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CoordinationResult {
    /// Priority-sorted recommendations (conflicts, errors, delegations).
    pub recommendations: Vec<Recommendation>,
    /// Per-pane insight summaries keyed by pane label (e.g. "pane-1").
    pub pane_summaries: Vec<(String, Vec<String>)>,
}

/// Types of coordination recommendations.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RecommendationType {
    FileConflict,
    ErrorAssist,
    CrossPaneSync,
    TaskComplete,
    /// A delegation completed and the coordinator should receive the handoff.
    DelegationReady,
}

impl RecommendationType {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::FileConflict => "file_conflict",
            Self::ErrorAssist => "error_assist",
            Self::CrossPaneSync => "cross_pane_sync",
            Self::TaskComplete => "task_complete",
            Self::DelegationReady => "delegation_ready",
        }
    }
}

/// A tracked file conflict with resolution state.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct TrackedConflict {
    pub file_path: String,
    pub panes_involved: Vec<String>,
    pub detected_at: chrono::DateTime<chrono::Utc>,
    pub resolution: Option<ConflictResolution>,
    pub resolved_at: Option<chrono::DateTime<chrono::Utc>>,
}

impl TrackedConflict {
    pub fn new(file_path: String, panes_involved: Vec<String>) -> Self {
        Self {
            file_path,
            panes_involved,
            detected_at: chrono::Utc::now(),
            resolution: None,
            resolved_at: None,
        }
    }

    pub fn is_resolved(&self) -> bool {
        self.resolution.is_some()
    }

    pub fn resolve(&mut self, resolution: ConflictResolution) {
        self.resolution = Some(resolution);
        self.resolved_at = Some(chrono::Utc::now());
    }
}

/// Manages file conflict detection and resolution across panes.
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize)]
pub struct ConflictResolver {
    #[serde(default)]
    tracked_conflicts: HashMap<String, TrackedConflict>,
    #[serde(default)]
    resolution_history: Vec<ConflictRecord>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ConflictRecord {
    pub file_path: String,
    pub resolution: ConflictResolution,
    pub resolved_at: chrono::DateTime<chrono::Utc>,
    pub panes_involved: Vec<String>,
}

impl ConflictResolver {
    pub fn new() -> Self {
        Self {
            tracked_conflicts: HashMap::new(),
            resolution_history: Vec::new(),
        }
    }

    pub fn detect_and_add_conflicts(
        &mut self,
        insights: &[ExtractedInsight],
    ) -> Vec<Recommendation> {
        let detected = detect_file_conflicts(insights);

        for recommendation in &detected {
            if recommendation.recommendation_type == RecommendationType::FileConflict {
                let file_path = recommendation
                    .description
                    .strip_prefix("Multiple agents modifying: ")
                    .unwrap_or(&recommendation.description)
                    .to_string();

                // clippy: entry API less readable here — separate check + insert is clearer
                #[allow(clippy::map_entry)]
                if !self.tracked_conflicts.contains_key(&file_path) {
                    let tracked = TrackedConflict::new(
                        file_path.clone(),
                        recommendation.panes_involved.clone(),
                    );
                    self.tracked_conflicts.insert(file_path, tracked);
                }
            }
        }

        detected
    }

    pub fn resolve_conflict(&mut self, file_path: &str, resolution: ConflictResolution) -> bool {
        if let Some(tracked) = self.tracked_conflicts.get_mut(file_path) {
            tracked.resolve(resolution);

            self.resolution_history.push(ConflictRecord {
                file_path: file_path.to_string(),
                resolution,
                resolved_at: chrono::Utc::now(),
                panes_involved: tracked.panes_involved.clone(),
            });

            true
        } else {
            false
        }
    }

    pub fn get_conflict_suggestions(&self, file_path: &str) -> Vec<String> {
        let mut suggestions = Vec::new();

        if let Some(tracked) = self.tracked_conflicts.get(file_path) {
            if let Some(resolution) = &tracked.resolution {
                suggestions.push(format!(
                    "Conflict for '{}' already resolved with: {}",
                    file_path,
                    resolution.description()
                ));
                return suggestions;
            }

            suggestions.push(format!(
                "File '{}' is being modified by {} panes",
                file_path,
                tracked.panes_involved.len()
            ));

            suggestions.push("Resolution options:".to_string());
            suggestions.push(format!(
                "  1. Merge: {}",
                ConflictResolution::Merge.description()
            ));
            suggestions.push(format!(
                "  2. AcceptTheirs: {}",
                ConflictResolution::AcceptTheirs.description()
            ));
            suggestions.push(format!(
                "  3. AcceptMine: {}",
                ConflictResolution::AcceptMine.description()
            ));
            suggestions.push(format!(
                "  4. Rebase: {}",
                ConflictResolution::Rebase.description()
            ));

            if tracked.panes_involved.len() == 2 {
                suggestions.push(
                    "Tip: Consider reviewing both versions in separate panes before merging"
                        .to_string(),
                );
            }
        } else {
            suggestions.push(format!("No tracked conflict found for '{}'", file_path));
        }

        suggestions
    }

    pub fn get_unresolved_conflicts(&self) -> Vec<&TrackedConflict> {
        self.tracked_conflicts
            .values()
            .filter(|c| !c.is_resolved())
            .collect()
    }

    pub fn get_resolved_conflicts(&self) -> Vec<&TrackedConflict> {
        self.tracked_conflicts
            .values()
            .filter(|c| c.is_resolved())
            .collect()
    }

    // Restored from cfg(test) gate — now wired to IPC (Task 20)
    pub fn get_resolution_history(&self) -> &[ConflictRecord] {
        &self.resolution_history
    }

    // Restored from cfg(test) gate — now wired to IPC (Task 20)
    pub fn clear_resolved(&mut self) {
        self.tracked_conflicts.retain(|_, c| !c.is_resolved());
    }
}

/// Detects file conflicts across panes (same file modified by multiple agents).
pub fn detect_file_conflicts(insights: &[ExtractedInsight]) -> Vec<Recommendation> {
    use std::collections::HashMap;

    // Group file modification insights by content (which contains the file path)
    let mut file_to_panes: HashMap<String, Vec<String>> = HashMap::new();
    for insight in insights {
        if insight.insight_type == InsightType::FileModified {
            file_to_panes
                .entry(insight.content.clone())
                .or_default()
                .push(format!("pane-{}", insight.pane_id));
        }
    }

    // Only flag when 2+ panes touch the same file
    file_to_panes
        .into_iter()
        .filter(|(_, panes)| panes.len() > 1)
        .map(|(file, panes)| Recommendation {
            recommendation_type: RecommendationType::FileConflict,
            panes_involved: panes,
            description: format!("Multiple agents modifying: {}", file),
            action: "Coordinate changes to avoid merge conflicts".to_string(),
            priority: default_priority(),
        })
        .collect()
}

/// Detects errors in one pane that might be caused by another pane's changes.
pub fn detect_cross_pane_errors(insights: &[ExtractedInsight]) -> Vec<Recommendation> {
    let errors: Vec<&ExtractedInsight> = insights
        .iter()
        .filter(|i| i.insight_type == InsightType::ErrorEncountered)
        .collect();

    let modifications: Vec<&ExtractedInsight> = insights
        .iter()
        .filter(|i| i.insight_type == InsightType::FileModified)
        .collect();

    let mut recommendations = Vec::new();

    for error in &errors {
        // Check if any other pane modified files around the same time
        let related_mods: Vec<&ExtractedInsight> = modifications
            .iter()
            .filter(|m| {
                m.pane_id != error.pane_id
                    && (error.timestamp - m.timestamp).num_seconds().abs() < 120
            })
            .copied()
            .collect();

        if !related_mods.is_empty() {
            let panes: Vec<String> = std::iter::once(format!("pane-{}", error.pane_id))
                .chain(related_mods.iter().map(|m| format!("pane-{}", m.pane_id)))
                .collect();

            let mod_files: Vec<&str> = related_mods.iter().map(|m| m.content.as_str()).collect();

            recommendations.push(Recommendation {
                recommendation_type: RecommendationType::ErrorAssist,
                panes_involved: panes,
                description: format!(
                    "Error in pane-{} may relate to changes in: {}",
                    error.pane_id,
                    mod_files.join(", ")
                ),
                action: format!(
                    "Check if recent modifications to {} caused: {}",
                    mod_files[0], error.content
                ),
                priority: default_priority(),
            });
        }
    }

    recommendations
}

/// Aggregate all insights into pane-keyed summaries for coordination prompts.
pub fn aggregate_pane_summaries(insights: &[ExtractedInsight]) -> Vec<(String, Vec<String>)> {
    use std::collections::BTreeMap;

    let mut pane_map: BTreeMap<usize, Vec<String>> = BTreeMap::new();
    for insight in insights {
        pane_map.entry(insight.pane_id).or_default().push(format!(
            "[{}] {}",
            insight.insight_type.as_str(),
            insight.content
        ));
    }

    pane_map
        .into_iter()
        .map(|(pid, summaries)| (format!("pane-{}", pid), summaries))
        .collect()
}

/// Detect delegation-related insights that need coordinator attention.
pub fn detect_delegation_events(insights: &[ExtractedInsight]) -> Vec<Recommendation> {
    insights
        .iter()
        .filter(|i| i.insight_type == InsightType::DelegationDetected)
        .map(|i| Recommendation {
            recommendation_type: RecommendationType::DelegationReady,
            panes_involved: vec![format!("pane-{}", i.pane_id)],
            description: format!("Delegation detected in pane-{}", i.pane_id),
            action: "Review delegation handoff and coordinate next steps".to_string(),
            priority: default_priority(),
        })
        .collect()
}

/// Compute the dominant intent across all insights that carry one.
/// Returns `None` if no insight has a classified intent.
fn dominant_intent(insights: &[ExtractedInsight]) -> Option<IntentCategory> {
    let mut counts: HashMap<IntentCategory, usize> = HashMap::new();
    for insight in insights {
        if let Some(cat) = &insight.intent {
            if *cat != IntentCategory::Unknown {
                *counts.entry(*cat).or_default() += 1;
            }
        }
    }
    counts.into_iter().max_by_key(|(_, c)| *c).map(|(k, _)| k)
}

/// Priority score for a recommendation given the dominant intent.
/// Lower score = higher priority (will sort first).
fn intent_priority(rec: &Recommendation, dominant: Option<IntentCategory>) -> u8 {
    let Some(intent) = dominant else {
        return 50; // neutral when no dominant intent
    };
    match intent {
        IntentCategory::Deploying => match rec.recommendation_type {
            RecommendationType::FileConflict => 0,
            RecommendationType::ErrorAssist => 1,
            RecommendationType::DelegationReady => 2,
            RecommendationType::CrossPaneSync => 3,
            RecommendationType::TaskComplete => 4,
        },
        IntentCategory::Testing => match rec.recommendation_type {
            RecommendationType::ErrorAssist => 0,
            RecommendationType::TaskComplete => 1,
            RecommendationType::FileConflict => 2,
            RecommendationType::DelegationReady => 3,
            RecommendationType::CrossPaneSync => 4,
        },
        IntentCategory::Debugging => match rec.recommendation_type {
            RecommendationType::ErrorAssist => 0,
            RecommendationType::FileConflict => 1,
            RecommendationType::CrossPaneSync => 2,
            RecommendationType::DelegationReady => 3,
            RecommendationType::TaskComplete => 4,
        },
        // For all other intents, use a default priority
        _ => match rec.recommendation_type {
            RecommendationType::FileConflict => 1,
            RecommendationType::ErrorAssist => 2,
            RecommendationType::DelegationReady => 3,
            RecommendationType::CrossPaneSync => 4,
            RecommendationType::TaskComplete => 5,
        },
    }
}

/// Run all local (non-LLM) coordination checks and return recommendations.
/// Recommendations are sorted by intent-based priority when insights carry
/// classified intents (e.g., Deploying elevates conflict/error warnings,
/// Testing/Debugging elevate error-assist recommendations).
pub fn run_local_coordination(insights: &[ExtractedInsight]) -> Vec<Recommendation> {
    let mut all = Vec::new();
    all.extend(detect_file_conflicts(insights));
    all.extend(detect_cross_pane_errors(insights));
    all.extend(detect_delegation_events(insights));

    let dominant = dominant_intent(insights);
    // Set priority field: map sort key (0=most urgent) to priority (100=most urgent)
    for rec in &mut all {
        let sort_key = intent_priority(rec, dominant) as u16;
        rec.priority = 100u8.saturating_sub((sort_key * 20).min(100) as u8);
    }
    all.sort_by(|a, b| b.priority.cmp(&a.priority));
    all
}

/// Run all local coordination checks *and* aggregate pane summaries.
///
/// This is the full pipeline for daemon responses — it returns both the
/// priority-sorted recommendations and the per-pane insight summaries that
/// callers (GUI, CLI) can display alongside recommendations.
pub fn run_full_coordination(insights: &[ExtractedInsight]) -> CoordinationResult {
    let recommendations = run_local_coordination(insights);
    let pane_summaries = aggregate_pane_summaries(insights);
    CoordinationResult {
        recommendations,
        pane_summaries,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::context_lifecycle::types::AgentKind;
    use chrono::Utc;

    fn make_insight(pane_id: usize, insight_type: InsightType, content: &str) -> ExtractedInsight {
        ExtractedInsight {
            pane_id,
            agent_kind: AgentKind::ClaudeCode,
            timestamp: Utc::now(),
            insight_type,
            content: content.to_string(),
            intent: None,
        }
    }

    #[test]
    fn test_detect_file_conflicts_none() {
        let insights = vec![
            make_insight(1, InsightType::FileModified, "src/main.rs"),
            make_insight(2, InsightType::FileModified, "src/lib.rs"),
        ];
        let conflicts = detect_file_conflicts(&insights);
        assert!(conflicts.is_empty());
    }

    #[test]
    fn test_detect_file_conflicts_found() {
        let insights = vec![
            make_insight(1, InsightType::FileModified, "src/main.rs"),
            make_insight(2, InsightType::FileModified, "src/main.rs"),
        ];
        let conflicts = detect_file_conflicts(&insights);
        assert_eq!(conflicts.len(), 1);
        assert_eq!(
            conflicts[0].recommendation_type,
            RecommendationType::FileConflict
        );
        assert_eq!(conflicts[0].panes_involved.len(), 2);
    }

    #[test]
    fn test_detect_cross_pane_errors() {
        let now = Utc::now();
        let insights = vec![
            ExtractedInsight {
                pane_id: 1,
                agent_kind: AgentKind::ClaudeCode,
                timestamp: now,
                insight_type: InsightType::FileModified,
                content: "src/lib.rs".to_string(),
                intent: None,
            },
            ExtractedInsight {
                pane_id: 2,
                agent_kind: AgentKind::OpenCode,
                timestamp: now,
                insight_type: InsightType::ErrorEncountered,
                content: "cannot find module lib".to_string(),
                intent: None,
            },
        ];
        let errors = detect_cross_pane_errors(&insights);
        assert_eq!(errors.len(), 1);
        assert_eq!(
            errors[0].recommendation_type,
            RecommendationType::ErrorAssist
        );
    }

    #[test]
    fn test_aggregate_pane_summaries() {
        let insights = vec![
            make_insight(1, InsightType::FileModified, "src/main.rs"),
            make_insight(1, InsightType::TaskCompleted, "tests pass"),
            make_insight(2, InsightType::ErrorEncountered, "compile error"),
        ];
        let summaries = aggregate_pane_summaries(&insights);
        assert_eq!(summaries.len(), 2);
        assert_eq!(summaries[0].0, "pane-1");
        assert_eq!(summaries[0].1.len(), 2);
        assert_eq!(summaries[1].0, "pane-2");
        assert_eq!(summaries[1].1.len(), 1);
    }

    #[test]
    fn test_run_local_coordination_empty() {
        let recs = run_local_coordination(&[]);
        assert!(recs.is_empty());
    }

    #[test]
    fn test_recommendation_type_as_str() {
        assert_eq!(RecommendationType::FileConflict.as_str(), "file_conflict");
        assert_eq!(RecommendationType::ErrorAssist.as_str(), "error_assist");
        assert_eq!(
            RecommendationType::CrossPaneSync.as_str(),
            "cross_pane_sync"
        );
        assert_eq!(RecommendationType::TaskComplete.as_str(), "task_complete");
    }

    #[test]
    fn test_conflict_resolution_as_str() {
        assert_eq!(ConflictResolution::Merge.as_str(), "merge");
        assert_eq!(ConflictResolution::AcceptTheirs.as_str(), "accept_theirs");
        assert_eq!(ConflictResolution::AcceptMine.as_str(), "accept_mine");
        assert_eq!(ConflictResolution::Rebase.as_str(), "rebase");
    }

    #[test]
    fn test_conflict_resolution_description() {
        assert_eq!(
            ConflictResolution::Merge.description(),
            "Manually merge changes from both agents"
        );
        assert_eq!(
            ConflictResolution::AcceptTheirs.description(),
            "Accept the other agent's changes"
        );
        assert_eq!(
            ConflictResolution::AcceptMine.description(),
            "Keep my changes"
        );
        assert_eq!(
            ConflictResolution::Rebase.description(),
            "Rebase on top of other agent's changes"
        );
    }

    #[test]
    fn test_conflict_resolver_new() {
        let resolver = ConflictResolver::new();
        assert!(resolver.get_unresolved_conflicts().is_empty());
        assert!(resolver.get_resolution_history().is_empty());
    }

    #[test]
    fn test_conflict_resolver_detect_and_add_conflicts() {
        let insights = vec![
            make_insight(1, InsightType::FileModified, "src/main.rs"),
            make_insight(2, InsightType::FileModified, "src/main.rs"),
            make_insight(1, InsightType::FileModified, "src/lib.rs"),
        ];

        let mut resolver = ConflictResolver::new();
        let recommendations = resolver.detect_and_add_conflicts(&insights);

        assert_eq!(recommendations.len(), 1);
        assert_eq!(
            recommendations[0].recommendation_type,
            RecommendationType::FileConflict
        );

        let unresolved = resolver.get_unresolved_conflicts();
        assert_eq!(unresolved.len(), 1);
        assert_eq!(unresolved[0].file_path, "src/main.rs");
        assert!(!unresolved[0].is_resolved());
    }

    #[test]
    fn test_conflict_resolver_resolve_conflict() {
        let insights = vec![
            make_insight(1, InsightType::FileModified, "src/main.rs"),
            make_insight(2, InsightType::FileModified, "src/main.rs"),
        ];

        let mut resolver = ConflictResolver::new();
        resolver.detect_and_add_conflicts(&insights);

        let result = resolver.resolve_conflict("src/main.rs", ConflictResolution::Merge);
        assert!(result);

        let unresolved = resolver.get_unresolved_conflicts();
        assert!(unresolved.is_empty());

        let resolved = resolver.get_resolved_conflicts();
        assert_eq!(resolved.len(), 1);
        assert_eq!(resolved[0].resolution, Some(ConflictResolution::Merge));

        let history = resolver.get_resolution_history();
        assert_eq!(history.len(), 1);
        assert_eq!(history[0].resolution, ConflictResolution::Merge);
    }

    #[test]
    fn test_conflict_resolver_resolve_nonexistent() {
        let mut resolver = ConflictResolver::new();
        let result = resolver.resolve_conflict("nonexistent.rs", ConflictResolution::AcceptMine);
        assert!(!result);
    }

    #[test]
    fn test_conflict_resolver_get_conflict_suggestions() {
        let insights = vec![
            make_insight(1, InsightType::FileModified, "src/main.rs"),
            make_insight(2, InsightType::FileModified, "src/main.rs"),
        ];

        let mut resolver = ConflictResolver::new();
        resolver.detect_and_add_conflicts(&insights);

        let suggestions = resolver.get_conflict_suggestions("src/main.rs");
        assert!(!suggestions.is_empty());
        assert!(suggestions[0].contains("src/main.rs"));
        assert!(suggestions.iter().any(|s| s.contains("Merge")));
        assert!(suggestions.iter().any(|s| s.contains("AcceptTheirs")));
        assert!(suggestions.iter().any(|s| s.contains("AcceptMine")));
        assert!(suggestions.iter().any(|s| s.contains("Rebase")));
    }

    #[test]
    fn test_conflict_resolver_get_conflict_suggestions_resolved() {
        let insights = vec![
            make_insight(1, InsightType::FileModified, "src/main.rs"),
            make_insight(2, InsightType::FileModified, "src/main.rs"),
        ];

        let mut resolver = ConflictResolver::new();
        resolver.detect_and_add_conflicts(&insights);
        resolver.resolve_conflict("src/main.rs", ConflictResolution::Rebase);

        let suggestions = resolver.get_conflict_suggestions("src/main.rs");
        assert!(suggestions.len() == 1);
        assert!(suggestions[0].contains("already resolved"));
        assert!(suggestions[0].contains("Rebase"));
    }

    #[test]
    fn test_conflict_resolver_clear_resolved() {
        let insights = vec![
            make_insight(1, InsightType::FileModified, "src/main.rs"),
            make_insight(2, InsightType::FileModified, "src/main.rs"),
            make_insight(3, InsightType::FileModified, "src/lib.rs"),
            make_insight(4, InsightType::FileModified, "src/lib.rs"),
        ];

        let mut resolver = ConflictResolver::new();
        resolver.detect_and_add_conflicts(&insights);

        assert_eq!(resolver.get_unresolved_conflicts().len(), 2);

        resolver.resolve_conflict("src/main.rs", ConflictResolution::AcceptMine);

        assert_eq!(resolver.get_unresolved_conflicts().len(), 1);

        resolver.clear_resolved();

        assert_eq!(resolver.get_unresolved_conflicts().len(), 1);
        assert!(resolver.get_resolved_conflicts().is_empty());
    }

    #[test]
    fn test_tracked_conflict_is_resolved() {
        let conflict = TrackedConflict::new("src/main.rs".to_string(), vec!["pane-1".to_string()]);
        assert!(!conflict.is_resolved());

        let mut resolved_conflict = conflict;
        resolved_conflict.resolve(ConflictResolution::Merge);
        assert!(resolved_conflict.is_resolved());
        assert!(resolved_conflict.resolved_at.is_some());
    }

    // ─── Intent-based priority tests ─────────────────────────────────

    fn make_insight_with_intent(
        pane_id: usize,
        insight_type: InsightType,
        content: &str,
        intent: Option<IntentCategory>,
    ) -> ExtractedInsight {
        ExtractedInsight {
            pane_id,
            agent_kind: AgentKind::ClaudeCode,
            timestamp: Utc::now(),
            insight_type,
            content: content.to_string(),
            intent,
        }
    }

    #[test]
    fn test_dominant_intent_none_when_empty() {
        let insights: Vec<ExtractedInsight> = vec![];
        assert_eq!(dominant_intent(&insights), None);
    }

    #[test]
    fn test_dominant_intent_none_when_all_none() {
        let insights = vec![
            make_insight(1, InsightType::FileModified, "src/main.rs"),
            make_insight(2, InsightType::ErrorEncountered, "compile error"),
        ];
        assert_eq!(dominant_intent(&insights), None);
    }

    #[test]
    fn test_dominant_intent_ignores_unknown() {
        let insights = vec![make_insight_with_intent(
            1,
            InsightType::FileModified,
            "some_file",
            Some(IntentCategory::Unknown),
        )];
        assert_eq!(dominant_intent(&insights), None);
    }

    #[test]
    fn test_dominant_intent_picks_most_frequent() {
        let insights = vec![
            make_insight_with_intent(
                1,
                InsightType::FileModified,
                "src/main.rs",
                Some(IntentCategory::Deploying),
            ),
            make_insight_with_intent(
                2,
                InsightType::FileModified,
                "src/lib.rs",
                Some(IntentCategory::Testing),
            ),
            make_insight_with_intent(
                3,
                InsightType::ToolInvocation,
                "cargo test",
                Some(IntentCategory::Testing),
            ),
        ];
        assert_eq!(dominant_intent(&insights), Some(IntentCategory::Testing));
    }

    #[test]
    fn test_deploying_intent_boosts_conflict_priority() {
        let now = Utc::now();
        // Create insights with Deploying intent + a file conflict + a cross-pane error
        let insights = vec![
            ExtractedInsight {
                pane_id: 1,
                agent_kind: AgentKind::ClaudeCode,
                timestamp: now,
                insight_type: InsightType::FileModified,
                content: "src/main.rs".to_string(),
                intent: Some(IntentCategory::Deploying),
            },
            ExtractedInsight {
                pane_id: 2,
                agent_kind: AgentKind::OpenCode,
                timestamp: now,
                insight_type: InsightType::FileModified,
                content: "src/main.rs".to_string(),
                intent: Some(IntentCategory::Deploying),
            },
            ExtractedInsight {
                pane_id: 3,
                agent_kind: AgentKind::Codex,
                timestamp: now,
                insight_type: InsightType::ErrorEncountered,
                content: "deploy failed".to_string(),
                intent: Some(IntentCategory::Deploying),
            },
            // Pane 1 also modified a file recently so cross-pane error is detected
            ExtractedInsight {
                pane_id: 1,
                agent_kind: AgentKind::ClaudeCode,
                timestamp: now,
                insight_type: InsightType::FileModified,
                content: "src/deploy.rs".to_string(),
                intent: Some(IntentCategory::Deploying),
            },
        ];

        let recs = run_local_coordination(&insights);
        assert!(!recs.is_empty());

        // When deploying, FileConflict should have highest priority (100)
        let conflict = recs
            .iter()
            .find(|r| r.recommendation_type == RecommendationType::FileConflict);
        assert!(
            conflict.is_some(),
            "should have a file conflict recommendation"
        );
        assert_eq!(conflict.unwrap().priority, 100);
    }

    #[test]
    fn test_testing_intent_boosts_error_priority() {
        let now = Utc::now();
        let insights = vec![
            ExtractedInsight {
                pane_id: 1,
                agent_kind: AgentKind::ClaudeCode,
                timestamp: now,
                insight_type: InsightType::FileModified,
                content: "src/main.rs".to_string(),
                intent: Some(IntentCategory::Testing),
            },
            ExtractedInsight {
                pane_id: 2,
                agent_kind: AgentKind::OpenCode,
                timestamp: now,
                insight_type: InsightType::FileModified,
                content: "src/main.rs".to_string(),
                intent: Some(IntentCategory::Testing),
            },
            ExtractedInsight {
                pane_id: 3,
                agent_kind: AgentKind::Codex,
                timestamp: now,
                insight_type: InsightType::ErrorEncountered,
                content: "test failed".to_string(),
                intent: Some(IntentCategory::Testing),
            },
            ExtractedInsight {
                pane_id: 1,
                agent_kind: AgentKind::ClaudeCode,
                timestamp: now,
                insight_type: InsightType::FileModified,
                content: "src/test_utils.rs".to_string(),
                intent: Some(IntentCategory::Testing),
            },
        ];

        let recs = run_local_coordination(&insights);
        assert!(!recs.is_empty());

        // When testing, ErrorAssist should have highest priority (100)
        let error_assist = recs
            .iter()
            .find(|r| r.recommendation_type == RecommendationType::ErrorAssist);
        assert!(
            error_assist.is_some(),
            "should have an error assist recommendation"
        );
        assert_eq!(error_assist.unwrap().priority, 100);

        // FileConflict should be lower priority than ErrorAssist
        let conflict = recs
            .iter()
            .find(|r| r.recommendation_type == RecommendationType::FileConflict);
        assert!(conflict.is_some());
        assert!(conflict.unwrap().priority < error_assist.unwrap().priority);
    }

    #[test]
    fn test_no_intent_uses_default_priority() {
        let now = Utc::now();
        let insights = vec![
            ExtractedInsight {
                pane_id: 1,
                agent_kind: AgentKind::ClaudeCode,
                timestamp: now,
                insight_type: InsightType::FileModified,
                content: "src/main.rs".to_string(),
                intent: None,
            },
            ExtractedInsight {
                pane_id: 2,
                agent_kind: AgentKind::OpenCode,
                timestamp: now,
                insight_type: InsightType::FileModified,
                content: "src/main.rs".to_string(),
                intent: None,
            },
        ];

        let recs = run_local_coordination(&insights);
        assert_eq!(recs.len(), 1);
        // No dominant intent → neutral priority (100 - 50*0 = depends on neutral arm)
        // Neutral arm returns 50, so priority = 100 - 50*20 → clamped
        // Actually neutral returns 50 for all types, so priority = 100 - 50*20 = saturating_sub → 0
        // Wait, let me check: intent_priority returns 50 when no dominant intent
        // priority = 100u8.saturating_sub(50 * 20) = 100 - 1000 → saturating → 0
        assert_eq!(recs[0].priority, 0);
    }

    // ─── run_full_coordination tests ────────────────────────────────

    #[test]
    fn test_run_full_coordination_empty() {
        let result = run_full_coordination(&[]);
        assert!(result.recommendations.is_empty());
        assert!(result.pane_summaries.is_empty());
    }

    #[test]
    fn test_run_full_coordination_returns_both_recs_and_summaries() {
        let now = Utc::now();
        let insights = vec![
            ExtractedInsight {
                pane_id: 1,
                agent_kind: AgentKind::ClaudeCode,
                timestamp: now,
                insight_type: InsightType::FileModified,
                content: "src/main.rs".to_string(),
                intent: None,
            },
            ExtractedInsight {
                pane_id: 2,
                agent_kind: AgentKind::OpenCode,
                timestamp: now,
                insight_type: InsightType::FileModified,
                content: "src/main.rs".to_string(),
                intent: None,
            },
            ExtractedInsight {
                pane_id: 2,
                agent_kind: AgentKind::OpenCode,
                timestamp: now,
                insight_type: InsightType::ErrorEncountered,
                content: "compile error in main.rs".to_string(),
                intent: None,
            },
        ];

        let result = run_full_coordination(&insights);

        // Should have file conflict + cross-pane error
        assert!(
            !result.recommendations.is_empty(),
            "should produce recommendations"
        );
        let has_conflict = result
            .recommendations
            .iter()
            .any(|r| r.recommendation_type == RecommendationType::FileConflict);
        let has_error = result
            .recommendations
            .iter()
            .any(|r| r.recommendation_type == RecommendationType::ErrorAssist);
        assert!(has_conflict, "should detect file conflict");
        assert!(has_error, "should detect cross-pane error");

        // Should have 2 pane summaries (pane-1 and pane-2)
        assert_eq!(
            result.pane_summaries.len(),
            2,
            "should have 2 pane summaries"
        );
        assert_eq!(result.pane_summaries[0].0, "pane-1");
        assert_eq!(result.pane_summaries[1].0, "pane-2");
        // pane-1 has 1 insight, pane-2 has 2 insights
        assert_eq!(result.pane_summaries[0].1.len(), 1);
        assert_eq!(result.pane_summaries[1].1.len(), 2);
    }

    #[test]
    fn test_run_full_coordination_no_duplicate_recs_for_same_file() {
        let now = Utc::now();
        // Pane 1 and 2 modify same file (conflict).
        // Pane 2 also has an error (cross-pane error related to pane 1's modification).
        // These are distinct recommendation types and should NOT be deduplicated.
        let insights = vec![
            ExtractedInsight {
                pane_id: 1,
                agent_kind: AgentKind::ClaudeCode,
                timestamp: now,
                insight_type: InsightType::FileModified,
                content: "src/lib.rs".to_string(),
                intent: Some(IntentCategory::Deploying),
            },
            ExtractedInsight {
                pane_id: 2,
                agent_kind: AgentKind::OpenCode,
                timestamp: now,
                insight_type: InsightType::FileModified,
                content: "src/lib.rs".to_string(),
                intent: Some(IntentCategory::Deploying),
            },
            ExtractedInsight {
                pane_id: 2,
                agent_kind: AgentKind::OpenCode,
                timestamp: now,
                insight_type: InsightType::ErrorEncountered,
                content: "linker error".to_string(),
                intent: Some(IntentCategory::Deploying),
            },
        ];

        let result = run_full_coordination(&insights);

        // Count recommendation types
        let conflict_count = result
            .recommendations
            .iter()
            .filter(|r| r.recommendation_type == RecommendationType::FileConflict)
            .count();
        let error_count = result
            .recommendations
            .iter()
            .filter(|r| r.recommendation_type == RecommendationType::ErrorAssist)
            .count();

        // Exactly 1 file conflict and 1 error assist — no duplicates
        assert_eq!(conflict_count, 1, "should have exactly 1 file conflict rec");
        assert_eq!(error_count, 1, "should have exactly 1 error assist rec");

        // With Deploying intent, conflict should be highest priority
        let conflict = result
            .recommendations
            .iter()
            .find(|r| r.recommendation_type == RecommendationType::FileConflict)
            .unwrap();
        let error = result
            .recommendations
            .iter()
            .find(|r| r.recommendation_type == RecommendationType::ErrorAssist)
            .unwrap();
        assert!(
            conflict.priority >= error.priority,
            "deploying: conflict priority ({}) should >= error priority ({})",
            conflict.priority,
            error.priority
        );
    }

    #[test]
    fn test_coordination_result_serialization() {
        let result = CoordinationResult {
            recommendations: vec![Recommendation {
                recommendation_type: RecommendationType::FileConflict,
                panes_involved: vec!["pane-1".to_string(), "pane-2".to_string()],
                description: "Multiple agents modifying: src/main.rs".to_string(),
                action: "Coordinate changes".to_string(),
                priority: 100,
            }],
            pane_summaries: vec![
                (
                    "pane-1".to_string(),
                    vec!["[file_modified] src/main.rs".to_string()],
                ),
                (
                    "pane-2".to_string(),
                    vec!["[file_modified] src/main.rs".to_string()],
                ),
            ],
        };

        let json = serde_json::to_string(&result).unwrap();
        let parsed: CoordinationResult = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.recommendations.len(), 1);
        assert_eq!(parsed.pane_summaries.len(), 2);
        assert_eq!(
            parsed.recommendations[0].recommendation_type,
            RecommendationType::FileConflict
        );
    }
}
