use anyhow::Result;
use std::path::Path;
use std::sync::Arc;

use crate::envelope::{write_envelope, EnvelopeBuilder, OutputFormat};
use crate::{branding, credentials, memory, orchestration, state, storage};

use super::{
    build_tool_registry, print_config, refresh_capabilities_manifest, require_arg,
    tool_resolution_root,
};

/// Handle the `config` command.
///
/// Dispatches to get, set, or list operations depending on the provided
/// arguments. With no args, lists all config and prints usage hints.
pub fn handle_config(
    state: &Arc<state::State>,
    key: Option<String>,
    value: Option<String>,
    list: bool,
) -> Result<()> {
    if list {
        let config = state.list_config()?;
        print_config(config);
    } else if let Some(key) = key {
        if let Some(value) = value {
            match state.set_config(&key, &value) {
                Ok(true) => println!("Set {} = {}", key, value),
                Ok(false) => {
                    eprintln!("Error: Invalid value '{}' for key '{}'", value, key)
                }
                Err(e) => eprintln!("Error: {}", e),
            }
        } else {
            match state.get_config(&key)? {
                Some(v) => println!("{} = {}", key, v),
                None => println!("Unknown config key: {}", key),
            }
        }
    } else {
        let config = state.list_config()?;
        print_config(config);
        println!("\nUse 'config <key>' to get a value");
        println!("Use 'config <key> --value <value>' to set a value");
        println!("Use 'config --list' to list all values");
    }
    Ok(())
}

/// Handle the `init` command.
///
/// Creates the `.impulse/` directory structure including `LIVE_STATE.json`,
/// `GENOME.md`, `config.json`, context dirs, external tools dir, and the
/// capabilities manifest.
pub fn handle_init(state: &Arc<state::State>, impulse_dir: &Path) -> Result<()> {
    state
        .storage()
        .write_json("LIVE_STATE.json", &state::LiveState::new())?;
    state
        .storage()
        .write_json("GENOME.md", &memory::Genome::new())?;
    state
        .storage()
        .write_json("config.json", &state::Config::default())?;
    let _ = orchestration::ensure_context_dirs(state.storage().base_path())?;
    let config = state.config_snapshot()?;
    let external_tools_dir =
        config.resolved_external_tools_dir_from(tool_resolution_root(impulse_dir));
    std::fs::create_dir_all(&external_tools_dir)?;
    let registry = build_tool_registry(impulse_dir, &config)?;
    let manifest_path = refresh_capabilities_manifest(state.storage().base_path(), &registry)?;
    ensure_repo_runtime_ignores(impulse_dir)?;
    branding::print_banner();
    println!("Initialized at {:?}", state.storage().base_path());
    println!("External tools dir: {}", external_tools_dir.display());
    println!("Capabilities manifest: {}", manifest_path.display());
    Ok(())
}

/// Project-local files that are generated by a running Impulse instance and
/// must not make an otherwise clean governed Git subject appear dirty.
///
/// Deliberately absent are durable project artifacts such as `GENOME.md`,
/// `HISTORY.jsonl`, `config.json`, and `impulse-capabilities.json`.
const REPO_RUNTIME_GITIGNORE_ENTRIES: &[&str] = &[
    ".impulse/LIVE_STATE.json",
    ".impulse/SESSIONS.json",
    ".impulse/agent_history.jsonl",
    ".impulse/retrieval.db",
    ".impulse/retrieval.db-*",
    ".impulse/retrieval_index_state.json",
    ".impulse/retrieval.lock",
    ".impulse/embeddings/",
    ".impulse/sockets/",
    ".impulse/GOVERNED_TASKS.json",
    ".impulse/GOVERNED_TASKS.tmp.*",
    ".impulse/DESKTOP_GOVERNED_LIFECYCLE_OUTBOX.json",
    ".impulse/DESKTOP_GOVERNED_LIFECYCLE_OUTBOX.lock",
    ".impulse/DESKTOP_GOVERNED_LIFECYCLE_OUTBOX.tmp-*",
];

fn has_blanket_impulse_ignore(existing: &str) -> bool {
    existing.lines().any(|line| {
        matches!(
            line.trim(),
            ".impulse" | ".impulse/" | ".impulse/**" | "/.impulse" | "/.impulse/" | "/.impulse/**"
        )
    })
}

fn ensure_repo_runtime_ignores(impulse_dir: &Path) -> Result<()> {
    if impulse_dir.file_name().and_then(|name| name.to_str()) != Some(".impulse") {
        return Ok(());
    }
    let Some(repo_root) = impulse_dir.parent() else {
        return Ok(());
    };
    if !repo_root.join(".git").exists() {
        return Ok(());
    }

    let gitignore_path = repo_root.join(".gitignore");
    let existing = if gitignore_path.exists() {
        std::fs::read_to_string(&gitignore_path)?
    } else {
        String::new()
    };
    if has_blanket_impulse_ignore(&existing) {
        eprintln!(
            "Warning: existing .gitignore blanket-hides .impulse; Impulse preserves that operator rule, so durable GENOME/config/capabilities files remain ignored until you narrow it"
        );
    }
    let mut updated = existing.clone();
    for entry in REPO_RUNTIME_GITIGNORE_ENTRIES {
        if existing.lines().any(|line| line == *entry) {
            continue;
        }
        if !updated.is_empty() && !updated.ends_with('\n') {
            updated.push('\n');
        }
        updated.push_str(entry);
        updated.push('\n');
    }

    if updated != existing {
        storage::Storage::atomic_write_path(&gitignore_path, updated.as_bytes())?;
    }
    Ok(())
}

/// Handle the `status` command.
///
/// Prints the Impulse banner and lists all active sessions with their
/// names, IDs, and statuses. When format is Json/Ndjson, emits via envelope
/// (platforms array + multi-workspace note). Text mode prints human lines
/// that contain the required indicators (claude-code, codex, workspace).
pub async fn handle_status(state: &Arc<state::State>, format: Option<OutputFormat>) -> Result<()> {
    use impulse_ops::agent_registry::{AgentPlatformsReport, AgentRegistry};
    let sessions = state.list_sessions().await?;
    let reg = AgentRegistry::registry_for_runtime()?;
    let report = AgentPlatformsReport::from_registry(&reg);

    // Default to Text for human status (banner + indicators); json when explicitly requested.
    let fmt = format.unwrap_or(OutputFormat::Text);
    if matches!(fmt, OutputFormat::Json | OutputFormat::Ndjson) {
        let data = serde_json::json!({
            "active_sessions": sessions.len(),
            "sessions": sessions.iter().map(|s| {
                serde_json::json!({
                    "name": s.name,
                    "id": s.id,
                    "status": format!("{:?}", s.status)
                })
            }).collect::<Vec<_>>(),
            "agent_platforms": report.platforms,
            "multi_workspace_support": report.multi_workspace_note,
        });
        let env = EnvelopeBuilder::new("status").ok(data);
        write_envelope(fmt, &env)?;
    } else {
        branding::print_banner();
        println!("Active sessions: {}", sessions.len());
        for s in &sessions {
            println!("  - {} ({}) [{:?}]", s.name, s.id, s.status);
        }
        println!("\nRegistered agent platforms (from impulse-ops::AgentRegistry):");
        for p in &report.platforms {
            println!("  - {} ({}): command='{}'", p.id, p.label, p.command);
        }
        println!("Multi-workspace support: {}", report.multi_workspace_note);
    }
    Ok(())
}

/// Handle the `list-providers` command.
///
/// Prints all available LLM providers with their default models and
/// supported model lists.
pub fn handle_list_providers() -> Result<()> {
    use crate::agent::{AnthropicProvider, LlmProvider, MinimaxProvider, OpenAiProvider};

    println!("Available LLM Providers:\n");

    let anthropic = AnthropicProvider::new(String::new());
    let openai = OpenAiProvider::new(String::new());
    let minimax = MinimaxProvider::new(String::new());

    println!(
        "  {} (default: {})\n    Models: {}",
        anthropic.name(),
        anthropic.default_model(),
        anthropic.supported_models().join(", ")
    );
    println!(
        "\n  {} (default: {})\n    Models: {}",
        openai.name(),
        openai.default_model(),
        openai.supported_models().join(", ")
    );
    println!(
        "\n  {} (default: {})\n    Models: {}",
        minimax.name(),
        minimax.default_model(),
        minimax.supported_models().join(", ")
    );
    Ok(())
}

/// Handle the `model` command (list/set/get subcommands).
///
/// Lists cached models, sets a default model for a provider, or retrieves
/// the currently configured model for a given provider.
pub fn handle_model(
    state: &Arc<state::State>,
    _impulse_dir: &Path,
    verbose: bool,
    subcommand: String,
    provider: Option<String>,
    model: Option<String>,
) -> Result<()> {
    use crate::docs::cache;
    use crate::docs::models as model_mgr;

    match subcommand.as_str() {
        "list" | "ls" => {
            let cache = cache::create_cache(state.storage().base_path())?;
            let models = cache.load_models().unwrap_or_else(|_| Vec::new());

            let filter = model_mgr::ModelFilter {
                provider: provider.clone(),
                ..Default::default()
            };

            let filtered = filter.apply(&models);
            println!("{}", model_mgr::format_models(&filtered, verbose));
        }
        "set" => {
            let provider = require_arg(provider, "provider")?;
            let model = require_arg(model, "model")?;
            state.set_config(&format!("model.{}", provider), &model)?;
            println!("Set default model for {} to {}", provider, model);
        }
        "get" => {
            let provider = require_arg(provider, "provider")?;
            let model = state.get_config(&format!("model.{}", provider))?;
            if let Some(m) = model {
                println!("{}: {}", provider, m);
            } else {
                let defaults = model_mgr::ModelConfig::default();
                if let Some(def) = defaults.get_default_model(&provider) {
                    println!("{} (default): {}", provider, def);
                } else {
                    println!("No model configured for {}", provider);
                }
            }
        }
        _ => {
            eprintln!(
                "Unknown model subcommand: {}. Use: list, set, get",
                subcommand
            );
        }
    }
    Ok(())
}

/// Handle the `credentials` command (list/get/set/delete/status subcommands).
///
/// Manages secrets through the configured credential provider (env, CLI tool,
/// or socket). Supports listing, reading, writing, and deleting secrets.
pub fn handle_credentials(
    subcommand: String,
    provider: Option<String>,
    key: Option<String>,
    value: Option<String>,
    socket_path: Option<String>,
    tool: Option<String>,
) -> Result<()> {
    use credentials::{create_provider, CredentialConfig, CredentialProviderType};

    let provider_type = provider
        .as_ref()
        .and_then(|p| CredentialProviderType::parse(p))
        .unwrap_or(CredentialProviderType::Env);

    let config = CredentialConfig {
        provider: provider_type,
        cli_tool: tool.clone(),
        socket_path: socket_path.clone(),
        provider_url: None,
    };

    let cred_provider = create_provider(&config);

    match subcommand.as_str() {
        "list" | "ls" => {
            let status = cred_provider.status();
            println!(
                "Provider: {} (available: {})",
                status.provider, status.available
            );

            match cred_provider.list() {
                Ok(secrets) => {
                    if secrets.is_empty() {
                        println!("No secrets stored.");
                    } else {
                        println!("\nStored secrets:");
                        for secret in secrets {
                            println!("  - {}", secret.key);
                        }
                    }
                }
                Err(e) => {
                    eprintln!("Error listing secrets: {}", e);
                }
            }
        }
        "get" => {
            let key = key
                .as_ref()
                .ok_or_else(|| anyhow::anyhow!("--key required"))?;
            match cred_provider.get(key) {
                Ok(val) => {
                    println!("{}", val);
                }
                Err(e) => {
                    eprintln!("Error getting secret: {}", e);
                }
            }
        }
        "set" => {
            let key = key
                .as_ref()
                .ok_or_else(|| anyhow::anyhow!("--key required"))?;
            let value = value
                .as_ref()
                .ok_or_else(|| anyhow::anyhow!("--value required"))?;
            match cred_provider.set(key, value) {
                Ok(_) => {
                    println!("Secret '{}' stored successfully.", key);
                }
                Err(e) => {
                    eprintln!("Error setting secret: {}", e);
                }
            }
        }
        "delete" | "rm" => {
            let key = key
                .as_ref()
                .ok_or_else(|| anyhow::anyhow!("--key required"))?;
            match cred_provider.delete(key) {
                Ok(_) => {
                    println!("Secret '{}' deleted.", key);
                }
                Err(e) => {
                    eprintln!("Error deleting secret: {}", e);
                }
            }
        }
        "status" => {
            let status = cred_provider.status();
            println!("Provider: {}", status.provider);
            println!("Available: {}", status.available);
            println!("Secrets count: {}", status.secrets_count);
            if let Some(err) = status.last_error {
                println!("Last error: {}", err);
            }
        }
        _ => {
            eprintln!(
                "Unknown credentials subcommand: {}. Use: list, get, set, delete, status",
                subcommand
            );
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;
    use tempfile::TempDir;

    fn test_state() -> (TempDir, Arc<state::State>) {
        let tmp = TempDir::new().unwrap();
        let st = state::State::new(tmp.path().to_path_buf()).unwrap();
        (tmp, Arc::new(st))
    }

    // ── handle_config: get/set/list ─────────────────────────────────────

    #[test]
    fn config_list_succeeds() {
        let (_tmp, st) = test_state();
        let result = handle_config(&st, None, None, true);
        assert!(result.is_ok());
    }

    #[test]
    fn config_get_known_key() {
        let (_tmp, st) = test_state();
        let result = handle_config(&st, Some("log_level".to_string()), None, false);
        assert!(result.is_ok());
    }

    #[test]
    fn config_get_unknown_key() {
        let (_tmp, st) = test_state();
        let result = handle_config(&st, Some("nonexistent".to_string()), None, false);
        assert!(result.is_ok());
    }

    #[test]
    fn config_set_valid() {
        let (_tmp, st) = test_state();
        let result = handle_config(
            &st,
            Some("log_level".to_string()),
            Some("debug".to_string()),
            false,
        );
        assert!(result.is_ok());
        let val = st.get_config("log_level").unwrap();
        assert_eq!(val, Some("debug".to_string()));
    }

    #[test]
    fn config_set_invalid_value() {
        let (_tmp, st) = test_state();
        let result = handle_config(
            &st,
            Some("log_level".to_string()),
            Some("verbose_mode".to_string()),
            false,
        );
        assert!(result.is_ok());
        let val = st.get_config("log_level").unwrap();
        assert_eq!(val, Some("info".to_string()));
    }

    #[test]
    fn config_no_args_shows_help() {
        let (_tmp, st) = test_state();
        let result = handle_config(&st, None, None, false);
        assert!(result.is_ok());
    }

    // ── handle_list_providers ───────────────────────────────────────────

    #[test]
    fn list_providers_succeeds() {
        let result = handle_list_providers();
        assert!(result.is_ok());
    }

    // ── handle_init ─────────────────────────────────────────────────────

    #[test]
    fn init_creates_files() {
        let (tmp, st) = test_state();
        let impulse_dir = tmp.path();
        let result = handle_init(&st, impulse_dir);
        assert!(result.is_ok());
        assert!(impulse_dir.join("LIVE_STATE.json").exists());
        assert!(impulse_dir.join("GENOME.md").exists());
        assert!(impulse_dir.join("config.json").exists());
    }

    #[test]
    fn init_appends_exact_repo_runtime_ignores_idempotently() {
        let repo = TempDir::new().unwrap();
        std::fs::create_dir(repo.path().join(".git")).unwrap();
        std::fs::write(repo.path().join(".gitignore"), "target/\ncustom.cache\n").unwrap();
        let impulse_dir = repo.path().join(".impulse");
        let st = Arc::new(state::State::new(impulse_dir.clone()).unwrap());

        handle_init(&st, &impulse_dir).unwrap();
        let first = std::fs::read_to_string(repo.path().join(".gitignore")).unwrap();
        handle_init(&st, &impulse_dir).unwrap();
        let second = std::fs::read_to_string(repo.path().join(".gitignore")).unwrap();

        assert_eq!(first, second, "repeated init must not duplicate entries");
        assert!(first.starts_with("target/\ncustom.cache\n"));
        for entry in REPO_RUNTIME_GITIGNORE_ENTRIES {
            assert_eq!(
                first.lines().filter(|line| line == entry).count(),
                1,
                "runtime ignore must appear exactly once: {entry}"
            );
        }
        assert!(!first.lines().any(|line| line == ".impulse/"));
        for durable in [
            ".impulse/GENOME.md",
            ".impulse/HISTORY.jsonl",
            ".impulse/config.json",
            ".impulse/impulse-capabilities.json",
        ] {
            assert!(
                !first.lines().any(|line| line == durable),
                "durable project artifact must remain commit-able: {durable}"
            );
        }
    }

    #[test]
    fn init_preserves_but_detects_an_existing_blanket_impulse_ignore() {
        let repo = TempDir::new().unwrap();
        std::fs::create_dir(repo.path().join(".git")).unwrap();
        std::fs::write(repo.path().join(".gitignore"), "target/\n.impulse/\n").unwrap();
        let impulse_dir = repo.path().join(".impulse");
        let st = Arc::new(state::State::new(impulse_dir.clone()).unwrap());

        handle_init(&st, &impulse_dir).unwrap();
        let gitignore = std::fs::read_to_string(repo.path().join(".gitignore")).unwrap();

        assert!(has_blanket_impulse_ignore(&gitignore));
        assert_eq!(
            gitignore
                .lines()
                .filter(|line| *line == ".impulse/")
                .count(),
            1,
            "init must warn about, not silently override, an operator-owned blanket rule"
        );
        for entry in REPO_RUNTIME_GITIGNORE_ENTRIES {
            assert!(gitignore.lines().any(|line| line == *entry));
        }
    }

    #[test]
    fn init_outside_repo_root_does_not_create_gitignore() {
        let (tmp, st) = test_state();

        handle_init(&st, tmp.path()).unwrap();

        assert!(!tmp.path().join(".gitignore").exists());
    }

    // ── handle_status ───────────────────────────────────────────────────

    #[tokio::test]
    async fn status_shows_no_sessions() {
        let (_tmp, st) = test_state();
        let result = handle_status(&st, None).await;
        assert!(result.is_ok());
    }

    // ── handle_model ────────────────────────────────────────────────────

    #[test]
    fn model_set_and_get() {
        let (tmp, st) = test_state();
        let result = handle_model(
            &st,
            tmp.path(),
            false,
            "set".to_string(),
            Some("anthropic".to_string()),
            Some("claude-3-5-sonnet".to_string()),
        );
        assert!(result.is_ok());

        let result = handle_model(
            &st,
            tmp.path(),
            false,
            "get".to_string(),
            Some("anthropic".to_string()),
            None,
        );
        assert!(result.is_ok());
    }

    #[test]
    fn model_set_missing_provider_fails() {
        let (tmp, st) = test_state();
        let result = handle_model(
            &st,
            tmp.path(),
            false,
            "set".to_string(),
            None,
            Some("gpt-4".to_string()),
        );
        assert!(result.is_err());
    }

    #[test]
    fn model_unknown_subcommand() {
        let (tmp, st) = test_state();
        let result = handle_model(&st, tmp.path(), false, "invalid".to_string(), None, None);
        assert!(result.is_ok());
    }
}
